# Configuration specific to taget reports
target:
  car_wash_csv: '/Users/jvm/Desktop/pws/fluidlytix_code/autobell/autobell_25/autobell_sample/autobell_etl/assets/autobell_25_original.csv'
  trg_start_date_col: 'start_date'
  trg_end_date_col: 'end_date'
  trg_start_meter_cubic_col: 'start_meter_cubic'
  trg_end_meter_cubic_col: 'end_meter_cubic'
  trg_cars_col: 'cars'
  trg_prelim_cols: ['start_date','end_date', 'start_meter_cubic', 'end_meter_cubic','cars']
  trg_days_col: 'days'
  trg_consumption_cubic_col: 'consumption_cubic'
  trg_start_meter_gallon_col: 'start_meter_gal'
  trg_end_meter_gallon_col: 'end_meter_gal'
  trg_consumption_gallon_col: 'consumption_gal'
  trg_gallons_car_col: 'gallons_car'
  trg_conversion_factor:  748.05
  trg_pre_install_annual_water_expense: 31876.00
  trg_contract_savings_rate: 15.00
  trg_primary_fluidlytix_cost: 5500.00
  trg_secondary_fluidlytix_cost: 5000.00 

# Configuration specific to test period reports
test: 
  test_period_start_date: '4/7/2022'
  test_period_end_date: '5/4/2022'
  test_period_start_meter_cubic: 43358.00
  test_period_end_meter_cubic: 43653.00
  test_period_cars: 11684.00

# Configuration specific to dates 
date:
  src_date_format: '%m/%d/%Y'
  trg_date_format: '%Y-%m-%d'

# Configuration specific to comparison reports
comparison:
  test_period_days_col: 'test_period_days'
  pre_install_cars_col: 'cars_pre_install'
  test_period_cars_col: 'cars_test_period'
  percent_diff_cars_col: 'percent_diff_cars'
  pre_install_consumption_col: 'consumption_pre_install'
  test_period_consumption_col: 'consumption_test_period'
  percent_diff_consumption_col: 'percent_diff_consumption'
  pre_install_gallons_car_col: 'gallons_car_pre_install'
  test_period_gallons_car_col: 'gallons_car_test_period'
  percent_diff_gallons_car_col: 'percent_diff_gallons_car'

# Configuration specific to savings + breakeven report
save-bep:
  annual_water_bill_col: 'annual_water_bill'
  savings_rate_col: 'savings_rate'
  monthly_savings_col: 'monthly_savings'
  annual_savings_col: 'annual_savings'
  ten_year_savings_col: 'savings_10_year'
  breakeven_point_col: 'bep_months'
  fluidlytix_cost_col: 'fluidlytix_project_cost'

# Configuration specific to cash flow report
cashflow:
  year_col: 'year'
  cash_flow_col: 'cash_flow'
  year_col_values: ['project_install', 'year_1', 'year_2', 'year_3', 'year_4', 'year_5', 'year_6', 'year_7', 'year_8', 'year_9', 'year_10']

#Logging Configuration 

logging:
  version: 1
  formatters:
    autobell:
      format: "Autobell ETL - %(asctime)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: autobell
      level: DEBUG
  root:
    level: DEBUG
    handlers: [console]